export const blogPosts = [
  {
    id: 1,
    category: 'Music Videos',
    image: '/blog-images/music-video.png',
    title: 'Sick blog post about music videos.',
    author: 'Cameron Cox',
    date: '19/04/2024',
  },
  {
    id: 2,
    category: 'Weddings',
    image: '/blog-images/wedding.png',
    title: 'How CCPV capture all the special moments on your big day.',
    author: 'Cameron Cox',
    date: '12/04/2024',
  },
  {
    id: 3,
    category: 'Corporate',
    image: '/blog-images/corporate.png',
    title: 'The importance of visual content when marketing your product.',
    author: 'Cameron Cox',
    date: '14/04/2024',
  },
  {
    id: 4,
    category: 'Sports',
    image: '/blog-images/sports.png',
    title: 'What makes great sporting event media coverage.',
    author: 'Cameron Cox',
    date: '19/04/2024',
  },
  {
    id: 5,
    category: 'Exhibitions',
    image: '/blog-images/exhibition.png',
    title: 'Telling your brand story beyond the Exhibition.',
    author: 'Cameron Cox',
    date: '12/04/2024',
  },
];
